language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t romana_m/react-class -f Dockerfile.dev .
script:
  - docker run CI=true romana_m/react-class npm run test -- --coverage